modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Bridges/issues"

[[mods]]
    modId="yungsbridges"
    version="${file.jarVersion}"
	displayName="YUNG's Bridges"
    credits="Thanks so much to all my patrons for their support!"
    authors="YUNGNICKYOUNG"
    description="Adds naturally occurring bridges throughout the world!"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-bridges"

[[dependencies.yungsbridges]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"

[[dependencies.yungsbridges]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.yungsbridges]]
    modId="yungsapi"
    versionRange="[1.19.2-Forge-3.5.0,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"